repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0  # the release, git tag, or commit you want to use
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-yaml
      - id: detect-private-key

  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout